name: Jira-webhook

on: push # 모든 브랜치에 대해 실행됩니다.

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Shell Script
        run: |
          cd $GITHUB_WORKSPACE/.github/workflows
          ./send-jira-webhook.sh
